//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JaegerLogic
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JaegerDB : DbContext
    {
        public JaegerDB()
            : base("name=JaegerDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Abschussliste> Abschussliste { get; set; }
        public virtual DbSet<Dokumente> Dokumente { get; set; }
        public virtual DbSet<Jaeger> Jaeger { get; set; }
        public virtual DbSet<Jagderfolge> Jagderfolge { get; set; }
        public virtual DbSet<Login> Login { get; set; }
        public virtual DbSet<Passwörter> Passwörter { get; set; }
        public virtual DbSet<Postausgang> Postausgang { get; set; }
        public virtual DbSet<Rueckmeldung> Rueckmeldung { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Termine> Termine { get; set; }
        public virtual DbSet<Tiere> Tiere { get; set; }
    }
}
