//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JaegerLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Termine
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Termine()
        {
            this.Jagderfolge = new HashSet<Jagderfolge>();
            this.Postausgang = new HashSet<Postausgang>();
            this.Rueckmeldung = new HashSet<Rueckmeldung>();
        }
    
        public int ID { get; set; }
        public string Typ { get; set; }
        public System.DateTime DatumUhrzeit { get; set; }
        public string Ort { get; set; }
        public string Bezeichnung { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Jagderfolge> Jagderfolge { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Postausgang> Postausgang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rueckmeldung> Rueckmeldung { get; set; }
    }
}
